env:
  node: true
  commonjs: true
  es2021: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-self-compare: warn
  no-unmodified-loop-condition: warn
  no-unreachable-loop: warn
  camelcase: warn
  capitalized-comments:
    - warn
    - always
  curly:
    - warn
    - all